---
- name: Sample ACI config
  hosts: aci
  connection: local
  gather_facts: True
  vars_files:
    - var_files/vars.yml

  tasks:
  - name: Add a new Tenant
    aci_tenant:
      hostname: "{{inventory_hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      tenant: DevNetCreate
      description: Awesome tenant
      state: present
      validate_certs: false