#simple IOS config in ansible
---
- name: Sample IOS config
  hosts: podiosv
  connection: local
  gather_facts: True
  vars_files:
    - var_files/vars.yml
  tasks:

  - name: set ACL via CLI
    ios_config:
      host: "{{inventory_hostname}}"
      username: "{{csr_username}}"
      password: "{{csr_password}}"
      lines:
        - 10 permit ip host 1.1.1.1 any log
        - 20 permit ip host 2.2.2.2 any log
        - 30 permit ip host 3.3.3.3 any log
        - 40 permit ip host 4.4.4.4 any log
        - 50 permit ip host 5.5.5.5 any log
      parents: ['ip access-list extended pod_{{pod}}_acl']


  - name: set ntp server via CLI
    ios_config:
      host: "{{inventory_hostname}}"
      username: "{{csr_username}}"
      password: "{{csr_password}}"
      lines: 
        - ntp server 1.1.1.{{pod}}


