---

- name: leaf configuration
  hosts: nxos
  connection: local
  gather_facts: no
  vars_files:
    - var_files/vars.yml

  tasks:

    ############################################################
    #  VLAN CONFIGURATION
    ############################################################
    - name: ensure VLANs exist on switches
      nxos_vlan: vlan_range="2-19,99" state=present host={{ inventory_hostname }} username={{ username }} password={{ password }}

    - name: ensure names exist for important vlans
      nxos_vlan: vlan_id={{ item.vlan_id }} name={{ item.name }} host={{ inventory_hostname }} state=present username={{ username }} password={{ password }}
      with_items:
        - { vlan_id: 10, name: test_segment }
        - { vlan_id: 99, name: native }


    #############################################################
    # Layer 2 switchport configs
    #############################################################
    - name: L2 config for uplinks
      nxos_switchport: interface={{ item }} mode=trunk native_vlan=99 trunk_vlans=2-19 host={{ inventory_hostname }} username={{ username }} password={{ password }}
      with_items:
        - Ethernet1/49
        - Ethernet1/50