---
- name: Create config output directory
  file:
    path: "{{ config_output_directory }}"
    state: directory

# You can iterate through via Variable
- name: Generate ASR Configuration Files
  template:
    src: router_full.j2.with_items
    dest: "{{ config_output_directory }}/{{item.device_name}}.txt"
  with_items: '{{podcsr}}'
  run_once: true

