feature_list:
  - interface-vlan
  - nxapi
  - vrrp

vrf_list:
  - { vrf: Red, next_hop: "{{ v101_cidr | ipaddr('4') | ipaddr('address') }}" }
  - { vrf: Blue, next_hop: "{{ v201_cidr | ipaddr('4') | ipaddr('address') }}" }

ntp_list:
  - "{{ntp_1}}"
  - "{{ntp_2}}"

vlans: [30,100,101,200,201,300]

named_vlans:
  - { vlan_id: 100, name: "Red: {{v100_cidr}}" }
  - { vlan_id: 101, name: "Red-Transition: {{v101_cidr}}" }
  - { vlan_id: 200, name: "Blue: {{v200_cidr}}" }
  - { vlan_id: 201, name: "Blue-Transition: {{v201_cidr}}" }

logical_interfaces_to_create:
  - { interface: vlan100,  description: Red, vrf: Red }
  - { interface: vlan101,  description: Red-Transition, vrf: Red }
  - { interface: vlan200,  description: Blue, vrf: Blue }
  - { interface: vlan201,  description: Blue-Transition, vrf: Blue }

hsrp:
  - { interface: vlan100,  vip: "{{ v100_cidr | ipaddr('1') | ipaddr('address') }}", group: 100  }
  - { interface: vlan101,  vip: "{{ v101_cidr | ipaddr('1') | ipaddr('address') }}", group: 101  }
  - { interface: vlan200,  vip: "{{ v200_cidr | ipaddr('1') | ipaddr('address') }}", group: 200  }
  - { interface: vlan201,  vip: "{{ v201_cidr | ipaddr('1') | ipaddr('address') }}", group: 201  }

trunked_links:
  - interface: Ethernet2/1
    vlans: "100,101,200,201"
    native_vlan: 30
  - interface: Ethernet2/2
    vlans: "100,101,200,201"
    native_vlan: 30
  - interface: Ethernet2/3
    vlans: "100,101,200,201"
    native_vlan: 30
