- name: Sample IOS automated CLI
  hosts: iospod
  vars_files:
    - var_files/ios_vars.yml

  tasks:

  - name: set ACL via CLI
    ios_config:
      host: "{{inventory_hostname}}"
      lines:
        - 10 permit ip host 1.1.1.1 any log
        - 20 permit ip host 2.2.2.2 any log
        - 30 permit ip host 3.3.3.3 any log
        - 40 permit ip host 4.4.4.4 any log
        - 50 permit ip host 5.5.5.5 any log
      parents: ['ip access-list extended pod_{{pod}}_acl']

  - name: set NTP server via CLI
    ios_config:
      lines:
        - ntp server 1.1.1.{{pod}}
