---
- name: NX-OS leaf configuration
  hosts: nxospod
  vars_files:
    - var_files/nxos_vars.yml

  tasks:

  - name: configure VLANs as defined in vars and host_vars
    nxos_vlan:
      aggregate: "{{ vlan_list }}"
      state: present
      purge: yes

  - name: L2 config for uplinks
    nxos_interface:
      aggregate: "{{l2_ports}}"
      mode: layer2
      admin_state: up

  - name: trunk config for uplinks
    nxos_l2_interface:
      aggregate: "{{trunk_ports}}"
