---
- name: Sample NX-OS NX-API
  hosts: nxosswitches
  gather_facts: no
  collections:
    - cisco.nxos

  tasks:

  - name: configure VLANs
    nxos_vlan:
      aggregate: "{{ vlan_list }}"
      state: present
      purge: yes

  - name: L2 config for uplinks
    nxos_interface:
      aggregate: "{{l2_ports}}"
      mode: layer2
      admin_state: up

  - name: trunk config for uplinks
    nxos_l2_interface:
      aggregate: "{{trunk_ports}}"
