---
- name: IOS
  hosts: iosrouters
  connection: local
  tasks:
    - debug: var=inventory_hostname
  roles:
    - ios_iac

- name: NXOS
  hosts: nxosswitches
  connection: local
  tasks:
    - debug: var=inventory_hostname
  roles:
    - nxos_iac
