---
- name: IOS
  hosts: iospod
  connection: local
  tasks:
    - debug: var=inventory_hostname
  roles:
    - ios_iac

- name: NXOS
  hosts: nxospod
  connection: local
  tasks:
    - debug: var=inventory_hostname
  roles:
    - nxos_iac
