---
  - name: configure vrf
    netconf_config:
      host: "{{inventory_hostname}}"
      username: "{{ansible_user}}"
      hostkey_verify: False
      password: "{{ansible_ssh_pass}}"
      xml: "{{vrf_template}}"
    with_items: "{{fabric}}" 
  - name: configure interfaces
    netconf_config:
      host: "{{inventory_hostname}}"
      username: "{{ansible_user}}"
      hostkey_verify: False
      password: "{{ansible_ssh_pass}}"
      xml: "{{int_template}}"
    with_items: "{{fabric}}"
    loop_control:
      pause: 5
