---
- name: Sample NETCONF config
  hosts: podiosv
  connection: local
  gather_facts: True
  vars_files:
    - var_files/vars.yml

  tasks:

    - name: set ntp server via NETCONF
      netconf_config:
        host: "{{inventory_hostname}}"
        username: "{{csr_username}}"
        hostkey_verify: False
        password: "{{csr_password}}"
        port: 10000
        xml: |
          <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"> 
           <system xmlns="urn:ietf:params:xml:ns:yang:ietf-system"> 
            <ntp>
             <enabled>true</enabled>
             <server>
              <name>ntp1</name>
              <udp><address>127.0.0.1</address></udp>
             </server>
            </ntp>
           </system>
          </config>
