---
- name: Create config output directory
  file:
    path: "{{ config_output_directory }}"
    state: directory

- name: Generate ASR Configuration Files
  template:
    src: asa_full.j2
    dest: "{{ config_output_directory }}/{{hostname}}.txt"

- asa_deploy:
    host: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    type: config
    protocol: ssh
    fname: "{{ config_output_directory }}/{{hostname}}.txt"
  ignore_errors: yes