---
- name: Sample NETCONF config
  hosts: podiosv
  connection: local
  gather_facts: True
  vars_files:
    - var_files/passwords.yml
    - var_files/vars.yaml
    - templates/nc_templates.yml
  tasks:

    - name: set ntp server via NETCONF with template
      netconf_config:
        host: "{{inventory_hostname}}"
        username: "{{username}}"
        hostkey_verify: False
        password: "{{password}}"
        xml: "{{xml_template}}"