---
- name: NX-OS ACL CFG Storage Clients In & Out
  hosts: nxos
  connection: local
  gather_facts: no
 
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: net_service.generic
      password: “x"
      transport: cli
 
  tasks:
    - name: 'ACL Storage Clients In'
      nxos_acl:
        name: storage-clients-in
        seq: 995
        action: permit
        proto: ip
        src: any
        dest: 10.109.33.0/24
        state: present 
        register: acl-in
    
    - name: 'ACL Storage Clients Out'
      nxos_acl:
        name: storage-clients-out
        seq: 995
        action: permit
        proto: ip
        src: 10.109.33.0/24
        dest: any
        state: present
        register: acl-out
 
    - debug:
        var: acl-in
    
    - debug:
        var: acl-out