
- hosts: spine
  vars_files: 
    - site_info.yml
  roles:
    - role: spine

- hosts: leaf
  roles:
    - role: leaf

- hosts: fw
  vars_files: 
    - site_info.yml
  roles:
    - role: asa

- hosts: xr
  vars_files: 
    - site_info.yml
  roles:
    - role: xr

