csr:
  mgmt_int: 'g2'
  mgmt_ip: '172.16.1.85'
  hostname: 'csr'
iosv:
  mgmt_int: 'g0/1'
  mgmt_ip: '172.16.1.83'
  hostname: 'iosv'
asav:
  mgmt_int: 'g0/0'
  mgmt_ip: '172.16.1.84'
  hostname: 'asav'
