#simple IOS config in ansible
---
- name: Prep ASA for REST
  hosts: allasav
  connection: local
  gather_facts: True
  vars_files:
    - passwords.yml
  tasks:

  #- command: "sshpass -p '{{password}}' scp ~/asa-restapi-121-lfbff-k8.SPA {{username}}@{{inventory_hostname}}:asa-restapi-121-lfbff-k8.SPA"

# This module is in the dev train and should be available in 2.2
  - asa_config:
     host: "{{inventory_hostname}}"
     username: "{{username}}"
     password: "{{password}}"
     auth_pass: "{{enablepass}}"
     authorize: True
     lines:
       - rest-api image disk0:asa-restapi-121-lfbff-k8.SPA
       - rest-api agent



