---

############################################################
#  FEATURE CONFIGURATION
############################################################
- name: ensure Features enabled on switches
  nxos_feature: feature={{ item }} state=enabled host={{ inventory_hostname }}
  with_items: feature_list

############################################################
#  NTP CONFIGURATION
############################################################
- name: ensure NTP exist on switches
  nxos_ntp: server={{ item }} vrf_name=management host={{ inventory_hostname }}
  with_items: ntp_list

############################################################
#  VLAN CONFIGURATION
############################################################
- name: ensure VLANs exist on switches
  nxos_vlan: vlan_id={{ item }} state=present host={{ inventory_hostname }}
  with_items: vlans

#- name: ensure names exist for important vlans
#  nxos_vlan: vlan_id={{ item.vlan_id }} name={{ item.name }} host={{ inventory_hostname }} state=present
#  with_items: named_vlans

#############################################################
# Layer 2 Switchport Configs
#############################################################
- nxos_interface: interface={{ item.interface }} mode=layer2 admin_state=up host={{ inventory_hostname }}
  with_items: trunked_links

- name: L2 config for all ports except peer keepalive
  nxos_switchport: interface={{ item.interface }} mode=trunk native_vlan={{ item.native_vlan }} trunk_vlans={{ item.vlans }} host={{ inventory_hostname }}
  with_items: trunked_links


#############################################################
# Layer 3 Configuration
#############################################################
############################################################
#  VRF CONFIGURATION
############################################################
- name: ensure VRFs exist on switches
  nxos_vrf: vrf={{ item.vrf }} host={{ inventory_hostname }}
  with_items: vrf_list

- name: create logical interfaces
  nxos_interface: interface={{ item.interface }} mode=layer3 admin_state=up host={{ inventory_hostname }} description={{ item.description }}
  with_items: logical_interfaces_to_create

- name: add interfaces to VRFs
  nxos_vrf_interface: vrf={{ item.vrf }} interface={{ item.interface }} host={{ inventory_hostname }} state=present
  with_items: logical_interfaces_to_create

- name: assign IP addresses
  nxos_ipv4_interface: interface={{ item.interface }} ip_addr={{ item.ip }} mask={{ item.mask }} host={{ inventory_hostname }}
  with_items: layer3ip

#- name: config VRRP
#  nxos_vrrp: group={{ item.group }} interface={{ item.interface }} vip={{ item.vip }} priority={{ hsrp_priority }} host={{ inventory_hostname }}
#  with_items: hsrp

############################################################
#  VRF ROUTE CONFIGURATION
############################################################
- name: ensure VRF routes exist on switches
  nxos_static_routes: prefix=0.0.0.0/0 next_hop={{ item.next_hop }} vrf={{ item.vrf }} host={{ inventory_hostname }}
  with_items: vrf_list

