---
# Interface variables
hostname: "{{site_name}}-fw"

red_vlan: 101
red_network: "{{ v101_cidr | ipaddr('network') }}"
red_netmask: "{{ v101_cidr | ipaddr('netmask') }}"
red_asa_ip: "{{ v101_cidr | ipaddr('4') | ipaddr('address') }}"
red_nh: "{{ v101_cidr | ipaddr('1') | ipaddr('address') }}"
red_host_network: "{{ v100_cidr | ipaddr('network') }}"

blue_vlan: 201
blue_asa_ip: "{{ v201_cidr | ipaddr('4') | ipaddr('address') }}"
blue_netmask: "{{ v201_cidr | ipaddr('netmask') }}"
blue_network: "{{ v201_cidr | ipaddr('network') }}"
blue_nh: "{{ v201_cidr | ipaddr('1') | ipaddr('address') }}"
blue_host_network: "{{ v200_cidr | ipaddr('network') }}"

outside_vlan: 300
outside_asa_ip: "{{ v300_cidr | ipaddr('4') | ipaddr('address') }}"
outside_netmask: "{{ v300_cidr | ipaddr('netmask') }}"
outside_network: "{{ v300_cidr | ipaddr('network') }}"
outside_nh: "{{ v300_cidr | ipaddr('1') | ipaddr('address') }}"