---
############################################################
#  VLAN CONFIGURATION
############################################################
- name: ensure VLANs exist on switches
  nxos_vlan: vlan_id={{ item }} state=present host={{ inventory_hostname }}
  with_items: vlans

#############################################################
# Layer 2 Switchport Configs
#############################################################
- nxos_interface: interface={{ item.interface }} mode=layer2 admin_state=up host={{ inventory_hostname }}
  with_items: trunked_links

- nxos_interface: interface={{ item.interface }} mode=layer2 admin_state=up host={{ inventory_hostname }}
  with_items: access_links

- name: L2 config for all trunked ports
  nxos_switchport: interface={{ item.interface }} mode=trunk native_vlan={{ item.native_vlan }} trunk_vlans={{ item.vlans }} host={{ inventory_hostname }}
  with_items: trunked_links

- nxos_switchport: interface={{ item.interface }} mode=access access_vlan={{ item.vlan }} host={{ inventory_hostname }}
  with_items: access_links